network:
  version: 2
  renderer: networkd
  ethernets:
    eno1:
      dhcp4: no
      dhcp6: no
      addresses:
        - "192.168.1.70/24"
        - "172.16.2.1/24"
      nameservers:
        addresses:
          - 1.1.1.1
          - 8.8.8.8
        search: []
      routes:
        - to: "default"
          via: "192.168.1.1"
