## mayastor issue
# Installed a 3 instance MySQL InnoDB cluster using mysql-innodb-mayastor-cluster.yaml. 
# It worked until I rebooted then had a problem like on rephub1_home.
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mycluster
spec:
  secretName: db-credentials
  tlsUseSelfSigned: true
  instances: 3
  router:
    instances: 1
  datadirVolumeClaimTemplate:
    storageClassName: mayastor
    accessModes: 
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
      