apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - name: mysql-nodeport
    nodePort: 30034
    port: 3306
    protocol: TCP
    targetPort: mysql-port
  selector:
    app: mysql
  type: NodePort