services:
  rstudio:
    image: rocker/verse:4
    ports:
      - "8787:8787"
    environment:
      PASSWORD: yourpassword
    volumes:
      - ./rstudio_config:/home/rstudio/.config/rstudio
      - ./workspace:/home/rstudio/workspace
      - ./other_dir:/other_dir
