apiVersion: v1
kind: Service
metadata:
  name: microk8s-console-np
  namespace: minio-operator
  ownerReferences:
  - apiVersion: minio.min.io/v2
    blockOwnerDeletion: true
    controller: true
    kind: Tenant
    name: microk8s
    uid: 49b5b277-8eb5-4c7d-9d42-5f21e1de6b8b
  resourceVersion: "1175803"
  uid: 3ea4b534-b941-4f8a-b908-4d03dd0a481e
spec:
  type: NodePort
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    v1.min.io/tenant: microk8s
  ports:
  - name: http-console-np
    nodePort: 30551  
    port: 9090
    protocol: TCP
    targetPort: 9090
