apiVersion: v1
kind: Service
metadata:
  labels:
    name: console
  name: console-np
  namespace: minio-operator
spec:
  type: NodePort
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    app: console
  ports:
  - name: http-np
    nodePort: 30551  
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: https-np
    nodePort: 30552  
    port: 9443
    protocol: TCP
    targetPort: 9443
