apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-10-30T23:09:21Z"
  name: tenant1-console
  namespace: example
  ownerReferences:
  - apiVersion: minio.min.io/v2
    blockOwnerDeletion: true
    controller: true
    kind: Tenant
    name: tenant1
    uid: eb4d604d-df6d-4ceb-8eec-93338252e3c2
  resourceVersion: "1709601"
  uid: 0b55076d-336d-4dee-a7b4-908fa5b48a44
spec:
  clusterIP: 10.152.183.96
  clusterIPs:
  - 10.152.183.96
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https-console
    port: 9443
    protocol: TCP
    targetPort: 9443
  selector:
    v1.min.io/tenant: tenant1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
