---
apiVersion: v1
kind: Service
metadata:
  name: tenant1-console-np
  namespace: example
spec:
  type: NodePort
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    v1.min.io/tenant: tenant1   
  ports:
  - name: https-console-np
    # A Service definition specifies the port number that the Service will listen on for incoming traffic using the port field. 
    port: 9443
    protocol: TCP
    # pod’s port number that the Service is responsible for routing traffic to
    targetPort: 9443
    nodePort: 30551
