---
apiVersion: v1
kind: Service
metadata:
  name: %APP%-%NODE%-svc
spec:
  ports:
  - name: %APP%-%NODE%-port
    port: %TARGET_PORT%
    targetPort: %NODE%-%TARGET_PORT_NAME%
    nodePort: %NODE_PORT%    
    protocol: TCP
