network:
  version: 2
  renderer: networkd
  ethernets:
    eno1:
      dhcp4: no
      addresses:
        - "192.168.1.65/24"
      routes:
        - to: "default"
          via: 192.168.1.1
      nameservers:
        addresses:
          - 192.168.1.1
          - 8.8.8.8
          - 8.8.4.4
  vlans:
    vlan10:
      id: 10
      link: eno1
      addresses:
        - "192.168.10.2/24"
    vlan20:
      id: 20
      link: eno1
      addresses:
        - "192.168.20.2/24"
