network:
  version: 2
  renderer: networkd
  ethernets:
    eno1:
      dhcp4: no
      dhcp6: no
      addresses:
        - "192.168.1.65/24"
      routes:
        - to: "default"
          via: 192.168.1.1
      nameservers:
        addresses:
          - 192.168.1.1
          - 1.1.1.1
          - 8.8.8.8
          - 8.8.4.4
    eno2:
      dhcp4: no
      dhcp6: no
      addresses:
        - "192.168.2.1/24"
      nameservers:
        addresses:
          - 192.168.1.1
          - 1.1.1.1
          - 8.8.8.8
          - 8.8.4.4
