apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: mysql-reports31-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  local:
    path: /mnt/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - reports31
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-storageclass
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-reports31-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: mysql-storageclass
  volumeMode: Filesystem
