---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: %APP%-%NODE%
  name: %APP%-%NODE%-svc
spec:
  selector:
    app: %APP%-%NODE%
  type: NodePort  
  ports:
  - name: %APP%-%NODE%-port
    port: %TARGET_PORT%
    targetPort: %NODE%-%TARGET_PORT_NAME%
    nodePort: %NODE_PORT%    
    protocol: TCP
