---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-rephub11
  name: mysql-rephub11-svc
spec:
  selector:
    app: mysql-rephub11
  type: NodePort  
  ports:
  - name: mysql-rephub11-port
    port: 3306
    targetPort: rephub11-mysql
    nodePort: 30031    
    protocol: TCP
