# https://github.com/kubernetes/website/issues/30912
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-reports33-pv
spec:
# https://stackoverflow.com/questions/60247100/hostpath-assign-persistentvolume-to-the-specific-work-node-in-cluster
# Don't need a persistent volume claim since this is a simple hostpath
# which can be set in the deployment
# https://kubernetes.io/blog/2017/03/advanced-scheduling-in-kubernetes/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - reports33  
