---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-follower-np
  namespace: ot-operators
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30381  # Choose a port that is free in your machine
  selector:
    app: redis-cluster-leader
    redis_setup_type: cluster
    role: leader