---
apiVersion: v1
kind: Service
metadata:
  name: redis-standalone-np
  namespace: ot-operators
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30379  # Choose a port that is free in your machine
  selector:
    app: redis