network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s25:
      dhcp4: no
      dhcp6: no
      addresses:
        - "192.168.2.83/24"
      routes:
        - to: "default"
          via: 192.168.2.1
      nameservers:
        addresses:
          - 192.168.1.1
          - 1.1.1.1
          - 8.8.8.8
          - 8.8.4.4
