---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-reports31
  labels:
    app: mysql-reports31
spec:
  serviceName: mysql-reports31-svc
  selector:
    matchLabels:
      app: mysql-reports31
  template:
    metadata:
      labels:
        app: mysql-reports31
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - reports31
      containers:
      - name: mysql-reports31
        image: brentgroves/mysql:8.0
        ports:
        - name: reports31-mysql
          containerPort: 3306
          protocol: TCP
        volumeMounts:
        - name: mysql-reports31-data-dir
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-reports31-data-dir
        persistentVolumeClaim:
          claimName: mysql-reports31-pvc
