apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lVSmpEbHBLL0RUTCt3T3h1UkppdjBDTVNucHhJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01NVEF1TVRVeUxqRTRNeTR4TUI0WERUSXlNVEF3T0RFM016STBNVm9YRFRNeQpNVEF3TlRFM016STBNVm93RnpFVk1CTUdBMVVFQXd3TU1UQXVNVFV5TGpFNE15NHhNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEwYmdOUUg3eTRDNEFXMXp3ZGh4dzk0TWJrelJnSlNjY1psL1MKV0ZBMnI4UTlPSnNmSUlPSHljQnhZamJNaHIwOW9Nblpkd2JwU0o2a0hDYWwvaFlBN0RvTmJBTEJSSXVzZGtzNwo3R3Q2ZE1RZzcxWmFYSkFvVVBYcitiQjZsNkdORm52aVFOTDVPRU04WUxqWGFzdzdYRkhvR0U1bW5kNVZna0xECmRGNWFKdHF0ckhobzdRVFFpalE2SDFVNzJ0WkZIS3VYR1QzZDNCL3Qzc2VuOStGd0VDeTB3ZnhOUXlWV3BNbEcKMmdybXYreXlhYkRXQTc1VlVObGYvcjRwUnlnL2Y3L21BRVFEaHdJT1RQM3RlTVJtSlpXMHpkeUFSMWdXSEtGbQpjUlhLenVyYWRUWEI1NkJkMDVZalRVOXdPbVNScTF6MmdTbUdha0VNdzg4Vkp3TVpOUUlEQVFBQm8xTXdVVEFkCkJnTlZIUTRFRmdRVTQvS3J5VGgvMXQ5RHdzOHFBRTk2RTF0ZmhQTXdId1lEVlIwakJCZ3dGb0FVNC9LcnlUaC8KMXQ5RHdzOHFBRTk2RTF0ZmhQTXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBemtqUE1lMEZodEtBS0g1N1pZS3NBRnF0ajZ3TmpFMTRLN2k2WDdTbC9vRmdDd1dwZVczSHpVRVV5U05DCjdBUTdZM0FxWmVwNFkrU0xhRFErWk5YTzBTd1UzYlRHQVJIcFlRQ2o4QnNFSUhvMW5lOGwvVlRGd2xMazRVclcKbmFmOHJJODYyTWlrZzdFUU5uSXE4eHpaeEVvOHZEcVg4am9qWVU0bFJoWDRiWkVQbTRHZnE2WjlLVEVjeVhzOQp3R01VVW55SUh6aGR1M3NBbk1kdTZLdW9obkdhbE5xaXBZdWZHaVFObE93TkFXT001MzliN241ZEtNbEoyOTNFCjNvaTQ1SXFwSkcrQVVLdUNpWTJpRjRST1hlMDExVFRHTFF1M0pPM1diWjltbGN0MzN0b2JLQ2JTVy9UUkRoakwKamhxMXhOOUVtUTNsMEJNQ0MrWHFrd2JUdEE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://10.1.1.83:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: K2JsbWRwM0V4cnduU0VJWXNCVENBNnhaV3psNXJMNU15NGRQYis2NU1tbz0K
