global:
  resolve_timeout: 5m
route:
  receiver: webhook_receiver
receivers:
    - name: webhook_receiver
      webhook_configs:
        - url: 'https://webhook.site/0745fb69-bd04-4694-8cac-0f59b968fe2c'
          send_resolved: false
