global:
  scrape_interval: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: hist_app
    static_configs:
      - targets: ["localhost:8080"]
  - job_name: simple_server
    static_configs:
      - targets: ["localhost:8090"]
