# https://stackoverflow.com/questions/78463004/rabbitmq-cluster-operator-and-loadbalancerip
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - name: amqp
      port: 5672
      protocol: TCP
      targetPort: 5672
  selector:
    app.kubernetes.io/name: resource-limits