apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/name: resource-limits
    app.kubernetes.io/part-of: rabbitmq
  name: resource-limits-np
spec:
  ports:
  - name: resource-limits-np
    nodePort: 32672
    port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app.kubernetes.io/name: resource-limits
  type: NodePort
---