apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/name: rabbitmqcluster-sample
    app.kubernetes.io/part-of: rabbitmq
  name: rabbitmqcluster-sample-np
spec:
  ports:
  - name: rabbitmqcluster-sample-np
    nodePort: 32672
    port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app.kubernetes.io/name: rabbitmqcluster-sample
  type: NodePort
---