network:
    ethernets:
        default:
            dhcp4: true
            match:
                macaddress: 52:54:00:14:9d:7b
        extra0:
            addresses:
              - 10.1.0.141/22
            nameservers:
                addresses:
                - 10.1.2.69
                - 10.1.2.70
                - 172.20.0.39
                search: [BUSCHE-CNC.COM]
            match:
                macaddress: 52:54:00:ff:17:97
            optional: true
    version: 2
