# https://github.com/kubernetes/website/issues/30912
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-reports33-pv
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-storageclass
  local:
    path: /mnt/data
