kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: innodb-retain
provisioner: disk.csi.azure.com
parameters:
  skuname: StandardSSD_LRS
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer