apiVersion: v1
kind: Service
metadata:
  name: mysql3-0
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: mysql3-0
  ports:
  - name: mysql3-0
    protocol: TCP
    nodePort: 30034
    port: 3306
    targetPort: mysql3-port
