apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
spec:
  containers:
  - name: mysql-container
    image: joseluisq/mysql-client
    command: ['sh','-c', "sleep 1800m"]
    imagePullPolicy: IfNotPresent