apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-set
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: brentgroves/mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql-port
          protocol: TCP
        volumeMounts:
        - name: mysql-store
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password3
              name: lastpass
        - name: TZ
          value: America/Fort_Wayne

  volumeClaimTemplates:
  - metadata:
      name: mysql-store
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "mayastor"
      resources:
        requests:
          storage: 5Gi

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysql-reports31-pvc
# spec:
#   storageClassName: mayastor
#   accessModes: [ReadWriteOnce]
#   resources: { requests: { storage: 5Gi } }          
