apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: rabbitmq-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  local:
    path: /mnt/rabbitmq
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - repsys11-c2-n1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rabbitmq-storageclass
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rabbitmq-storageclass
  volumeMode: Filesystem
