---
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel-np
  namespace: redis-sentinel
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30379  # Choose a port that is free in your machine
  selector:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: redis-sentinel
    app.kubernetes.io/name: redis
    # use same selector as svc/redis-sentinel-master -n redis-sentinel
    # app.kubernetes.io/component=master,
    # app.kubernetes.io/instance=redis-sentinel,
    # app.kubernetes.io/name=redis