---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: %APP%-%NODE%-pvc
spec:
  storageClassName: mysql-storageclass
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi

      
