# https://github.com/kubernetes/website/issues/30912
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-rephub11-pv
  labels:
    type: local
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - rephub11  
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-storageclass
  local:
    path: /mnt/mysql
