apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-reports11-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: openebs-jiva-csi-default
