---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: %APP_NAME%
spec:
  template:
    spec:
      containers:
      - image: brentgroves/mysql:8.0
        name: %APP_NAME%
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: TZ
          value: America/Fort_Wayne
      # https://stackoverflow.com/questions/60247100/hostpath-assign-persistentvolume-to-the-specific-work-node-in-cluster
      # Don't need a persistent volume claim since this is a simple hostpath
      # which can be set in the deployment
      affinity:               
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - %NODE_NAME%
