---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: %APP%-%NODE%
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: %APP%-%NODE%
        imagePullPolicy: Always
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: db-user-pass
        - name: TZ
          value: America/Fort_Wayne
