---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: %APP%-%NODE%
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: %APP%-%NODE%
        imagePullPolicy: Always
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password3
              name: lastpass
        - name: TZ
          value: America/Fort_Wayne
