---
apiVersion: v1
kind: Service
metadata:
  name: mysql-0
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: mysql-0
  ports:
  - name: mysql-0
    protocol: TCP
    nodePort: 30051
    port: 3306
    targetPort: mysql-port  
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
  clusterIP: None
  selector:
    app: mysql
