---
apiVersion: v1
kind: Service
metadata:
  name: %APP%-%ORDINAL%
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: %APP%-%ORDINAL%
  ports:
  - name: %APP%-%ORDINAL%
    protocol: TCP
    nodePort: %NODE_PORT%
    port: %TARGET_PORT%
    targetPort: %TARGET_PORT_NAME%  
---
apiVersion: v1
kind: Service
metadata:
  name: %APP%
  namespace: mysql
  labels:
    app: %APP%
spec:
  ports:
  - port: %TARGET_PORT%
  clusterIP: None
  selector:
    app: %APP%
