---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: brentgroves/mysql:8.0
        ports:
        - name: mysql-port
          containerPort: 3306
          protocol: TCP
        volumeMounts:
        - name: mysql-store
          mountPath: /var/lib/mysql
