
apiVersion: v1
kind: Service
metadata:
  name: mysql-frt
spec:
  selector:
    app: mysql-frt
  ports:
  - name: mysql-frt-port
    port: 3306
    targetPort: mysql-frt-svc
    nodePort: 30103    
    protocol: TCP
  type: NodePort  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-frt
spec:
  selector:
    matchLabels:
      app: mysql-frt
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-frt
    spec:
      # nodeName: reports3 # schedule pod to specific node
      containers:
      - image: brentgroves/mysql:8.0
        name: mysql-frt
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: TZ
          value: America/Fort_Wayne
        ports:
        - containerPort: 3306
          protocol: TCP
          name: mysql-frt-svc
        volumeMounts:
        - name: mysql-frt-persistent-storage
          mountPath: /var/lib/mysql
      # https://stackoverflow.com/questions/60247100/hostpath-assign-persistentvolume-to-the-specific-work-node-in-cluster
      # Don't need a persistent volume claim since this is a simple hostpath
      # which can be set in the deployment
      affinity:               
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - frt-ubu.busche-cnc.com
      volumes:
      - name: mysql-frt-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-frt-pv-claim
